# Generated by Django 3.0.6 on 2020-05-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'Student_Details'},
        ),
        migrations.AddField(
            model_name='student',
            name='student_file',
            field=models.FileField(default='NA', upload_to='documents'),
        ),
    ]
